### ISSUE TITLE
Heuristic analysis & User Testing

### ISSUE THREAD

**Issue by jbubar** [hackforla/VRMS#1138]
### Overview 
We are about to deploy the application, and it would be nice to have a list of all the things that should be changed to improve the user flow. That way we can chose to make changes or not repeat the same mistakes in v0.4.
This issue is a collection of notes from Design about the heuristics of the app, and feedback from user testing.

☑️ ready for dev
✅ dev has fixed already

### Action Items
- [x] Run the application locally
- [x] Make sure that you are an admin
- [x] Create user flow of current screens
- [x] Click around the application and conduct a heuristic analysis
- [x] Place your notes in the issue
- [x] Prioratize issues, and categorize: UX vs dev
- [x] Create smaller issues on Github and assign them
- [x] Usability Testing
  - [x] w/ Bonnie
  - [ ] w/ PM
- [ ] Continue checking heuristics and updating this issue

### Heuristic Evaluation
1.  (home) How important is it to display all the stats in Home? 
a. Which stats are most important?
2. (events) Clicking on meeting details also shows the same details (button is redundant). Can we add other important info (ex: zoom link, attendees, etc.)?
a. Clicking close doesn’t work. How can I go back to events list from there?
b. “Add event” only takes me to projects page
3. No scrolling feedback on any page
a. How far can you scroll on the events page? Does it loop around? It’s hard to know without any visual feedback
b. How can I search for a specific event? Can we add filter or search feature?
4. (admin) Why “add a new project” on admin page? Could probably just add a button or icon in the projects page instead? See issue:
https://github.com/hackforla/VRMS/issues/1105#issue-1196722136
a. Should the user be able to, not only input project name, but also edit the project (add description, team members, etc.) when it's being created instead of having to go to projects tab and then do it? See issue:
https://github.com/hackforla/VRMS/issues/1104#issue-1196718213
b. “Admin dashboard” could probably be a back arrow instead
5. (projects) How do I delete a project?
a. Can I search for a project?
6. (projects>selected project) Unnecessary edit buttons on project details. Is it possible to just have one “edit project” button that lets the user edit any field? Or maybe icons instead of the word edit?
a. Maybe it would be beneficial to have a display page and then a seperate edit page.
b. Can “back to select project” be a back arrow instead?
c. Will all the fields be used? Can we only have filled fields show up on the display page and then have all the fields appear when user wants to edit the project?
7. (admin>user management) Could probably improve filter elements on user management page. 
a. When I click “back to search” should it display the previous results searched?
8. Wording is confusing (events/meetings/projects). What is the difference between them, especially events and meetings?
a. Some other titles and copywrite could be improved. 
9. Check in as new user links to same page as create a new profile, so button is redundant.
10. (check-in) There is no back arrow to go to the previous page if user makes a mistake and wants to check in as new user instead of returning for ex.
a. What’s the purpose of checking into a meeting? Who gets this information/data? Where is it displayed (will/could it appear on the events page>meeting details?)

### Usability Testing 1 with Bonnie
**Task 1: Bonnie needs to add a new project**

1. User gets notified of new project created but then doesn’t know where to go to view the project that has just been created.
2. The project’s form fields need data validation, as opposed to them being free text fields.
a. Location: dropdown to preselected options
 1. Remote: links will be provided on the events of each project
 2. In person: a field appears to add an address
b. Github identifier: What if there’s multiple repos?
c. Google Drive ID: Is this field necessary?
d. Video Conference Link: This won’t be necessary on the projects page but only for the events created for a project.
e. Looking for description: We don’t need this field.
f. Recruiting Categories: We don’t need this field.
13. The “ Create New Event Button” is confusing. Layout and hierarchy needs to be improved.
a. Does this create an event for any project or the one the user is currently seeing?

**Task 2: Bonnie needs to assign a user to a project**

14. (admin>user management) Once a search result shows up the user doesn’t know where to click next to see the user details or continue with other tasks. Layout and hierarchy needs improvement. White space is tight and elements are too close together. 
a. The “Admin Dashboard” button calls the user to click it.
b. Does a user get notified when they’ve been added to a project?

**Task 3: Bonnie needs to remove a user from a project**

 15. (projects>selected project) UAL or member fields need to be added to the project page so the user can edit it from there as well.

**Task 4: Bonnie needs to add and edit project event time**

16. (events) The search feature should work using any word related to the event. Maybe we can add tags?
17. Users shouldn’t have to scroll all the way down to create another event. A button can be more accessible on the top.
18. Other filter options could be added to projects and user management pages to help the user search for and results.
19. Iconography and other components lack consistency and need improvement.
20. Reset button works with the information while it’s being edited in the modal but once the user clicks update, it doesn’t reset anymore.
21. Typography needs improvement. Type is too small, text hierarchy is missing.
22. We need to make sure we meet some accessibility and heuristic standards 

### Usability Testing 2 with Bonnie
**Task 1: Sign in to VRMS by following the prompts to arrive at the “Project Management” screen.**

1. The user was familiar with the process and had no trouble completing the task

**Task 2: Add a new project name “Testy Test” and its project details. Also, add some recurring team meeting times for this project. After you finish, return to the “Project Management” screen and make sure it is added to the database and stop there.**

2. Locations should be remote by default. ✅ 
    a. It wasn’t clear that was asking for a zoom link
3. She wasn’t sure what the github identifier is. 
    a. It should go after ‘Github URL’ if necessary. 
    b. You can use the API from the github url to fetch that ☑️
4. Placeholder names should give better examples of what the field requires 
5. The ‘Slack URL’ field is confusing. It should say “Slack channel URL” or be more specific about what kind of link is needed.✅ 
6. “Google drive URL” could be confusing for new users (not Bonnie). The drives have different URLs that can be fetched either from the main drive (ie VRMS) or the folder inside it (that was created so shortcuts could be used)
7. ‘HFLA website URL”, some projects may not be on the website yet. What is the workflow if the project is already created or isn’t?
8. *UX note: revise the wording. Make sure there is consistency.
9. *UX note: add members field is required too

**Task 3: Oops! You just realize that Testy Test’s Team Meeting 1 starts at 7PM vs. 8PM. Find project Testy Test and change the recurring Team Meeting 1 time to 7PM. After you finish, return to the “Project Management” screen and stop there.**

10. The user wants to save the project first before they create an event for it. 
11. *UX note: what does the flow look like when the user creates a project, saves it and then wants to add an event? What does the event creation form look like?

**Task 4: Find David Rubinstein with email [david@grubbylogic.com](mailto:david@grubbylogic.com) and add him to project Testy Test. After you finish, return to the “User Management” screen and stop there.**

12. A user could have multiple emails and that could create confusion. 
    a. It would be helpful to have an active/inactive label to differentiate between users with multiple email ☑️
13. *UX note: we need to add back buttons
14. *UX note: there is no current value to the notification modal as it is and it can be a pain point having to close it everytime.
    a. This could be solved by adding options or a next step into the notification modal
    b. Change the modal to just be a temporary bubble that doesn’t interfere and the user doesn't have to click to close it. 

**Task 5: David Rubinstein ([david@grubbylogic.com](mailto:david@grubbylogic.com)) just emailed you that he cannot be on project Testy Test. So, remove him from this project. After you finish, return to the “User Management” screen and stop there.**

15.  She didn’t know if she had to click save again after removing the project from David’s profile.

### Resources
https://www.figma.com/file/9c6pxjImN8MjHAZLH7zxYm/VRMS-Mocks?node-id=23726%3A2254
https://dev.vrms.io
[IMG_8227.pdf](https://github.com/hackforla/VRMS/files/8997789/IMG_8227.pdf)

**Comment by juliagab56** [comment]
Some notes from v3's heuristic analysis. Next step is comparing and prioritizing these issues with our new goals in mind.

**Comment by juliagab56** [comment]
Do we want to use this to improve v0.4 user experience?

**Comment by JudyLee533** [comment]
I am adding on to the issues from Bonnie's v3 usability testing on 10/3/22.

**Comment by juliagab56** [comment]
This issue is ongoing but we might be able to close it once we discuss it. We used it to gather pain points and heuristic information from VRMS and usability tests

**Comment by juliagab56** [comment]
Will need to transfer all research info to a doc and store it in the drive instead
