### ISSUE TITLE
Weekly Label and Milestones Audit

### ISSUE THREAD

**Issue by jbubar** [hackforla/VRMS#1169]
Overview
We need to perform a weekly check on issues to make sure they all conform to our label and milestone schema.

Action Items
Check the following to make sure that they are all 0/0 (Links for checking to make sure that all issues either have a ___ or a ____ missing label)
[Role](https://github.com/hackforla/VRMS/issues?q=is%3Aissue+label%3A%22role%3A+UI%2FUX+research%22+label%3A%22role%3A+UI%2FUX+design%22+label%3A%22role%3A+Product%22+label%3A%22role%3A+Org+Rep%22+label%3A%22role%3A+missing%22+label%3A%22role%3A+data+scientist%22+label%3A%22role%3A+intern%22+is%3Aopen+label%3A%22role%3A+UX+writer%22+label%3A%22role%3A+BA%22+label%3A%22role%3A+mentor%22+label%3A%22role%3A+Back+End%22+label%3A%22role%3A+Database%22+label%3A%22role%3A+devops%22+label%3A%22role%3A+Front+End%22+label%3A%22role%3A+Missing%22)
[size](https://github.com/hackforla/internship/issues?q=is%3Aopen+is%3Aissue+-label%3A%22size%3A+missing%22+-label%3A%22size%3A+1pt%22+-label%3A%22size%3A+2pt%22+-label%3A%22size%3A+3pt%22+-label%3A%22size%3A+5pt%22+-label%3A%22size%3A+8pt%22+-label%3A%22size%3A+13%2Bpt%22+-label%3A%22size%3A+0.5pt%22+-label%3A%22size%3A+0.25pt%22+-label%3A%22size%3A+0.50pt%22)
[feature](https://github.com/hackforla/internship/issues?q=is%3Aissue+-label%3A%22feature%3A+agenda%22+-label%3A%22feature%3A+calendar%22+-label%3A%22feature%3A+branding%22+-label%3A%22feature%3A+board+cleanup%22+-label%3A%22feature%3A+compliance%22+-label%3A%22feature%3A+deck%22+-label%3A%22feature%3A+C%26C+Analysis%22+-label%3A%22feature%3A+evangelize%22+-label%3A%22feature%3A+guide%22+-label%3A%22feature%3A+general+FAQ%22+-label%3A%22feature%3A+HfLA+volunteer+interviews%22+-label%3A%22feature%3A+hypothesis%22+-label%3A%22feature%3A+IS21%3A+Cohort+Analysis%22+-label%3A%22feature%3A+logo%22+-label%3A%22feature%3A+marketing+communication%22+-label%3A%22feature%3A+IS21+Cohort+Interviews%22+-label%3A%22feature%3A+marketing+plan%22+-label%3A%22feature%3A+marketing%22+-label%3A%22feature%3A+metrics%22+-label%3A%22feature%3A+missing%22+-label%3A%22feature%3A+one+sheet%22+-label%3A%22feature%3A+overview%22+-label%3A%22feature%3A+partner+communication%22+-label%3A%22feature%3A+partner+tracking%22+-label%3A%22feature%3A+presentation+templates%22+-label%3A%22feature%3A+project+FAQ%22+-label%3A%22feature%3A+project+listing%22+-label%3A%22feature%3A+recruitment%22+-label%3A%22feature%3A+research+plan%22+-label%3A%22feature%3A+roadmap%22+-label%3A%22feature%3A+stats%22+-label%3A%22feature%3A+test%22+-label%3A%22feature%3A+website%22+-label%3A%22feature%3A+wiki%22+-label%3A%22p-feature%3A+credits+page%22+-label%3A%22p-feature%3A+Linkedin+profile%22+-label%3A%22p-feature%3A+privacy+policy%22+-label%3A%22feaure%3A+HfLA+volunteer+analysis%22+-label%3A%22feature%3A+arrange+for+speaking+opportunities%22+-label%3A%22feature%3A+board+%2F+google+drive+%2F+tools%22+-label%3A%22feature%3A+find+speaking+opportunities%22+-label%3A%22feature%3A+HfLA%3A+presentation%22+-label%3A%22feature%3A+HfLA%3A+research+plan%22+-label%3A%22feature%3A+HfLA%3A+research+training%22+-label%3A%22feature%3A+HfLA%3A+volunteer+analysis%22+-label%3A%22feature%3A+HfLA%3A+volunteer+interviews%22+-label%3A%22feature%3A+HfLA%3A+volunteer+personas%22+-label%3A%22feature%3A+hypothesis+test%22+-label%3A%22feature%3A+IS21%3A+cohort+analysis%22+-label%3A%22feature%3A+IS21%3A+cohort+interviews%22+-label%3A%22feature%3A+IS21%3A+intern+personas%22+-label%3A%22feature%3A+IS21%3A+presentation%22+-label%3A%22feature%3A+onboarding%22+-label%3A%22feature%3A+IS21%3A+research+plan%22+-label%3A%22feature%3A+project+deck%22+-label%3A%22p-feature%3A+mentorship+guide%22+-label%3A%22p-feature%3A+networking+guide%22+-label%3A%22feature%3A+audience+development%22+-label%3A%22feature%3A+FAQ+for+Volunteers%22+-label%3A%22feature%3A+funding%22+-label%3A%22feature%3A+Intern+cohort+survey%22+-label%3A%22feature%3A+intern+personas%22+-label%3A%22feature%3A+IS22+cohort%22+-label%3A%22feature%3A+retention%22+-label%3A%22feature%3A+skills+assesment%22+-label%3A%22feature%3A+testing%22+-label%3A%22feature%3A+volunteer+onboarding%22+-label%3A%22p-feature%3A+FAQ+for+Interns%22+-label%3A%22p-feature%3A+recommendation+guide%22+-label%3A%22feature%3A+RP1%22+-label%3A%22feature%3A+RP2%22+-label%3A%22feature%3A+RP3%22+-label%3A%22feature%3A+RP4%22+-label%3A%22p-feature%3A+Resources+for+Interns%22+-label%3A%22feature%3A+research+audits%22+-label%3A%22feature%3A+research%22)
Add any label missing (e.g., a new feature label got added to the project, but didn't yet get added here) and update link
issues that have not yet been added to [project board](https://github.com/hackforla/internship/issues?q=is%3Aissue+is%3Aopen+no%3Aproject)
add to project board
if changes were made, recheck to make sure all links ended up 0/0
Audit for issues with Missing labels (to determine if we are making progress)
Copy this audit report format to a comment below

Date: 
- [ ] Did you have to update the 0/0 links above?  if yes, please say what you did (e.g, Added features to the features check above or added an issue to the project board that has not been added yet).
- [ ] Report what the numbers are on issues that are missing labels (e.g., size, ending at 12/5)
  - [ ] role, ending at
  - [ ] size, ending at
  - [ ] feature, ending at
  - [ ] milestone, ending at
### Resources/Instructions
REPLACE THIS TEXT - If there is a website that has documentation that helps with this issue provide the link(s) here.

**Comment by JackHaeg** [comment]
@jbubar can we delete this issue? I believe it's a duplicate of: https://github.com/hackforla/VRMS/issues/1168

**Comment by JackHaeg** [comment]
Closed issue, due to it being a duplicate
