### ISSUE TITLE
Design lo-fi user flow for all user stories

### ISSUE THREAD

**Issue by heyitsalexander** [hackforla/VRMS#1194]
### Overview
User Story #1: As a Project PM (permission: Project Level Admin), I need to be able to create and edit meeting times, so that I can keep HackforLA events page up-to-date. 

User Story #2: As Bonnie, I need to be able to edit user access levels to different projects, so that different volunteers have different admin permissions.

User Story #3: As Bonnie, I need to be able to add a new project, so that I can manage all the activities going on within HforLA.

User Story #4: As a volunteer, I need to be able to check-in using VRMS, so that HforLA can keep track of my involvement and attendance.

### Action Items
- [x] Create user flow to visualize user story #1197
- [x] Create user flow to visualize user story #1198 
- [x] Create user flow to visualize user story #1181 
- [ ] Create user flow to visualize user story #1182

### Resources/Instructions
[Figma](https://www.figma.com/file/VlsfGn1qZOAzpDymDQoTiy/VRMS-V4-Old-Files-(this-page-is-for-reference-only)?node-id=23823%3A2353)
[Style Guide](https://www.figma.com/file/2cwgCTKnLYl7OXhqsRZJsg/VRMS-Team-Library-%2B-Style-Guides?node-id=0%3A1)

**Comment by jbubar** [comment]
This looks like an epic of issues and all the issues have been completed

**Comment by ExperimentsInHonesty** [comment]
There is one open issue and it's in the icebox.  This issue is no longer needed.
