### ISSUE TITLE
As a Admin Level user, I want to be able to edit project information after I add it, so that I don't have to go looking for the project page again.

### ISSUE THREAD

**Issue by heyitsalexander** [hackforla/VRMS#1236]
### Overview
Currently, when the user adds a new project, VRMS does not automatically route the user to the project page. It is unclear to the user how to get to the relevant project page to start adding details.

### Action Items
- [x] Design team to redesign project page after Admin Level user adds a new project.
- [x] Dev team to review the new flow.
### Epic of Issues to fix. Check off as we go through each issue.
- [x] #1307
- [x] Implement Project management page
- [x] Implement Add project page
- [x] Implement Edit project page
- [x] Dev team to implement changes.

### Acceptance Criteria
Gherkin Syntax:
    Scenarios: All the actions a user could take (including bad input)
    GIVEN: Sets the context. What page are we on and what state are we in? Is the user an admin? Signed-in? Has created a campaign?
    WHEN: What actions the user is performing. What event occurred?
    THEN: What should the system do in response? What is the expected outcome?

Scenario: Admin Level user logs into VRMS
GIVEN that the user has Admin Level Access
WHEN they add a project and hit the add button
THEN the user should be able to immediately start editing project details
AND then save project details 
AND be able to retrieve that information in the future.

### Resources/Instructions
Zoom time stamp [1:11]
Zoom recording - https://drive.google.com/drive/u/0/folders/1oSUAaU-fzKHpXeZpou5PH3SwC5eRnEWq
<img width="508" alt="Screen Shot 2022-11-02 at 5 38 27 PM" src="https://user-images.githubusercontent.com/39230947/199867396-36600111-1099-47a0-a473-b1f2bec9888a.png">

**Comment by JudyLee533** [comment]
<img width="2679" alt="Issue 1236_ Current Flow" src="https://user-images.githubusercontent.com/107373945/214117038-4ac2bd32-46fa-45cc-be89-78d5735d0848.png">
<img width="2911" alt="Issue 1236_ Updated Flow" src="https://user-images.githubusercontent.com/107373945/214117087-5a4e5909-4133-4fd7-b255-dd37a7ef81d1.png">

**Comment by JudyLee533** [comment]
<img width="2882" alt="Sign-in Update_ Issue 1236" src="https://user-images.githubusercontent.com/107373945/214120341-654dd32f-d1bf-4ec3-b1f1-2dc0143710e5.png">

Adding the sign-in flow updated UI. Not sure if this is part of this issue. If not, we can start a new issue.

**Comment by MattPereira** [comment]
@plang-psm 

Moving this one to icebox since you are proposing that its primary purpose be organization

That way the `In Progress` column will contain only issues that devs are making PRs to solve and it will be easier for us to track who is actively working on what to prevent collisions

**Comment by juliagab56** [comment]
@JackHaeg This issue is somewhat resolved. The flow has improved and now the user is taken directly to the project page details of the project they just created. Not all UI has been implemented, but the UX has.

The issue needs more info on the dependecy and what to do to move it forward.

**Comment by trillium** [comment]
Closing as completed by @plang-psm via #1471
