### ISSUE TITLE
Server Responding With 502 Status Code

### ISSUE THREAD

**Issue by plang-psm** [hackforla/VRMS#1321]
### Dependency
- [x] #1872 has been resolved.

### Overview
A `Server not responding` alert is sometimes displayed to users after they select the `PROJECTS` tab from the navbar. The error is triggered after the frontend requests the `/api/projects/` endpoint from the server. The server responds with a `502` status code.

<details><summary>See screenshot of error</summary> 

![image](https://user-images.githubusercontent.com/73561520/223796797-0147760f-a2f7-4ef5-866b-5025d4609d7f.png)

</details>

### Action Items
- [x] Figure out who we need to communicate with to access AWS deployment information 
- [ ] Check #1323 to see if any of the completed issues resolved this one. If so, close this issue.
- [ ] Investigate the situation further and communicate findings with the team (note that the fix for #1872 may have also addressed this problem with server issues)
- [ ] Determine how to approach fixing the issue

### Phillip Notes
<details>
<summary>When clicking the ADMIN tab is selected</summary>
<br>
<img src='https://user-images.githubusercontent.com/101952500/223887941-252c10cd-dfa3-41a8-b69f-c4831f4c8a55.png' />

- Why is events being triggered via login?

</details>

<details>
<summary>When clicking the PROJECTS tab while the Dashboard is loading</summary>
<br>

<img src='https://user-images.githubusercontent.com/101952500/223893148-8865178f-a805-4cdc-8f81-62884a9d080e.png' />

- Why does /projects output 502 status codes but work when refreshed?
- Why is recurringEvents being triggered when you click Projects tab?

<img src='https://user-images.githubusercontent.com/101952500/223894217-022bb71a-4c08-4628-b9f9-f00d4a6e6fa9.png' />

- 2nd time running the error.

</details>

### Matt Notes
- The frontend is deployed with an Amazon Elastic Container Service
- Confusing how the production server only sometimes responds to `/api/projects` GET requests with the 502. 
- Since error never occurs in our local dev environment, problem may need to be addressed on AWS

### Instructions
Login to [dev.vrms.io](https://dev.vrms.io) as an admin user and visit the Projects List page, the server will sometimes respond with a `502` status code for the GET requests our frontend makes to the `/api/projects/` endpoint which results in the frontend `/projects` route failing to render the `ProjectList` component.

### Resources
- [AWS ECS logs for vrms-backend-prod service](https://us-west-2.console.aws.amazon.com/ecs/v2/clusters/incubator-prod/services/vrms-backend-prod/logs?region=us-west-2) ( login using credentials in VRMS 1Password vault )
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/502
- https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/http-502-bad-gateway.html

**Comment by MattPereira** [comment]
You may have some trouble recreating this error on dev.vrms.io but it does sometimes happen there especially if you access it in incgonito mode

The errors seem to occur much more frequently in production at vrms.io 

Both dev.vrms.io and vrms.io are currently deployed from the same commit

**Comment by MattPereira** [comment]
The frontend is deployed with an Amazon Elastic Container Service

Since this error never occurs in our local development environments, I suspect the issue may have something to do with our AWS deployment configuration

Adding this 502 error guide from AWS to the resources of this issue
- https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/http-502-bad-gateway.htmlS

**Comment by JackHaeg** [comment]
We probably need a milestone in the 04 series, for projects tab.

**Comment by JackHaeg** [comment]
Per @Spiteless, next steps would be to incorporate logging to figure out the issue.

**Comment by JackHaeg** [comment]
@Ganeshswaminathan1912 After completing work on #1872 would you mind taking a look at this issue, as I believe you already have been given access to our AWS?

**Comment by Tharunya07** [comment]
-- not happenign in dev so do not think it is in prod. can be closed.
