### ISSUE TITLE
Create phased development roadmap + MVP details

### ISSUE THREAD

**Issue by switchzer0** [hackforla/VRMS#135]
### Overview
Identify what is essential for MVP and timeline for subsequent phases

- [x] Approve phase elements
- [x] Detail phase elements
- [x] receive team approval

### Resources
First pass at deck: 

https://docs.google.com/presentation/d/1DLljKCoaoI2JSZUxL6oIOhBBXbSF30uW0EOgtYNSRrs/edit?usp=sharing

**Comment by switchzer0** [comment]
### Status
Reviewed on weekly team call. Team to provide comments in advance of Wednesday meeting with Bonnie, Cici, Matt, and Adam

### Next Steps
- Wednesday review call
- finalize high level plan
- detail MVP features and generate tickets

**Comment by switchzer0** [comment]
### Status
Revised deck based on feedback re duplicating website functionality and needing to reflect website as VRMS endpoint in some cases. New phasing recommendation is ready to go, pending team approval.
### Next Steps
Finalize direction with team
