### ISSUE TITLE
Epic - Form  - Remove Fields

### ISSUE THREAD

**Issue by heyitsalexander** [hackforla/VRMS#1371]
### Overview
Currently, the projects details form doesn't have any validation. It increases onboarding time because user needs to go back and frequently correct typos (Form validation)

The project’s form fields need data validation, as opposed to them being free text fields.
Updated form should look as follows:    

- [x] Google Drive ID: Needs to be removed 

- [x] Video Conference Link: Needs to be removed

- [x] Looking for description: Needs to be removed

- [x] Recruiting Categories: Needs to be removed
- [ ] #1728 - this was not completed, as requirements from stakeholder expressed a need for GitHub ID. (will keep on project details screen, not a required field in order to create/edit a project, and needs validation).

### Resources/Instructions
Usability Zoom Recording Timestamp 3:35
https://drive.google.com/drive/u/0/folders/1oSUAaU-fzKHpXeZpou5PH3SwC5eRnEWq
