### ISSUE TITLE
Adding Code of Conduct Feature to VRMS

### ISSUE THREAD

**Issue by AmandaGlover-PM** [hackforla/VRMS#1397]
### Dependency
This issue is for a future feature. We're not ready for it yet, it's not priority. 

### Overview
We need volunteers to be able to access and sign the Hack for LA Code of Conduct before the onboarding meeting in order to eliminate this as part of the process in onboarding meetings.  This will automate a major function of onboarding and reduce the onboarding meeting time by about 15 minutes.  This also means that signing the Code of Conduct is not manually done and enforced by Bonnie but is run automatically by VRMS.  The volunteer would express interest in Hack for LA, receive the Code of Conduct for review, would sign and submit the code of conduct and then receive meeting details for upcoming onboarding meetings.  This would need to be complete in order for them to receive the Zoom link for the live onboarding call.

### Action Items
- [ ] Check in with stakeholder Bonnie to confirm request at present and collaborate on next steps.
- [ ] Need to determine user flow - how would this need to function; how will this look and integrate into the VRMS app.
- [ ] Need to outline these process steps and create issues to build and complete the feature.

**Comment by juliagab56** [comment]
@JackHaeg this issue should be re-written for more clarity and to be more concise and it misses some resources, ie. screenshots or links.

**Comment by juliagab56** [comment]
Based on the latest mention in the Monday agenda, we should come up with specs and research first before going into detailed flows. Once we have clarity we can prioritize and start working on user flows. This will be part of the Onboarding feature which is an upcoming/new feature.
