### ISSUE TITLE
Epic: DB accepts capital and lower case email credentials for email login

### ISSUE THREAD

**Issue by trillium** [hackforla/VRMS#1456]
### Overview
Issue in the db where a user can register with a capital letter in their email and the db accepts that. Need to set user's email .toLowerCase() on the front end

Also need to set .toLowerCase() when database is queried

## Action Items
- [x] DevOps 
  - [x] Create feature branch `correct-db-casing`
- [x] Design
  - [x] #1464
  - [x] #1479
  - [x] #1551
  - [x] #1978 
  - [x] #1897 
  - [x] Execute Script
- [x] Test in Development
- [x] Execute on Production

**Comment by JackHaeg** [comment]
@Spiteless & @jbubar will write additional issues to breakdown next steps to complete this epic 
- [ ] Connecting to backend
- [ ] Propagating the changes so that the new User ID remains in all of the checkins

**Comment by JackHaeg** [comment]
@Spiteless & @jbubar When you have a chance, can you please write the additional issues Josh mentioned above so that we can unblock progress on this epic?

**Comment by JackHaeg** [comment]
@trilliumsmith & @jbubar When you have a chance, can you please write the additional issues Josh [mentioned above](https://github.com/hackforla/VRMS/issues/1456#issuecomment-2097283984) so that we can unblock progress on this epic?

> @trilliumsmith & @jbubar will write additional issues to breakdown next steps to complete this epic
> 
> * [ ]  Connecting to backend
> * [ ]  Propagating the changes so that the new User ID remains in all of the checkins

**Comment by JackHaeg** [comment]
Hi @trillium & @jbubar - checking in again! When you have a moment, can you please create the additional issues [mentioned above](https://github.com/hackforla/VRMS/issues/1456#issuecomment-2097283984) so that we can unblock progress on this epic?

> @trilliumsmith & @jbubar will write additional issues to breakdown next steps to complete this epic
> 
> * [ ]  Connecting to backend
> * [ ]  Propagating the changes so that the new User ID remains in all of the checkins

**Comment by JackHaeg** [comment]
Hi @trillium & @jbubar - checking in again! When you have a moment, can you please create the additional issues [mentioned above](https://github.com/hackforla/VRMS/issues/1456#issuecomment-2097283984) so that we can unblock progress on this epic?

> @trilliumsmith & @jbubar will write additional issues to breakdown next steps to complete this epic
> 
> * [ ]  Connecting to backend
> * [ ]  Propagating the changes so that the new User ID remains in all of the checkins

**Comment by JackHaeg** [comment]
Hi @jbubar just checking in again about this epic. When you have a moment, can you please create the additional issues [mentioned above](https://github.com/hackforla/VRMS/issues/1456#issuecomment-2097283984) so that we can unblock progress on this epic?

> @trillium  & @jbubar will write additional issues to breakdown next steps to complete this epic
> 
> * [ ]  Connecting to backend
> * [ ]  Propagating the changes so that the new User ID remains in all of the checkins

**Comment by JackHaeg** [comment]
Hi @trillium - just checking in on this issue again! When you have a moment, can you please create the additional issues [mentioned above](https://github.com/hackforla/VRMS/issues/1456#issuecomment-2097283984) so that we can unblock progress on this epic?

> @trilliumsmith & @jbubar will write additional issues to breakdown next steps to complete this epic
> 
> * [ ]  Connecting to backend
> * [ ]  Propagating the changes so that the new User ID remains in all of the checkins
