### ISSUE TITLE
BUG: Project details are not saving

### ISSUE THREAD

**Issue by JackHaeg** [hackforla/VRMS#1566]
### Overview
Users are unable to edit and save Project Information with an existing project (e.g., editing the GitHub Identifier, HFLA Website URL, Google Drive URL, etc.). Currently, when a user completes all of the required fields, they receive a "Sever not responding" error message > close the project > and when they return to the project, they are presented with the old / unedited project information.

### Action Items
- [x] Check to see what the current behavior is (see below screen recording)
- [x] Check to see if this issue is solved after completing #1565 (which would drop the "Location" requirement entirely)
- [x] Ensure that users with sufficient permissions (PMs, Admins) can edit an existing project's data

### Resources/Instructions

https://github.com/hackforla/VRMS/assets/134463646/f2c22b17-738d-4a5f-98db-891af8887957

**Comment by bkmorgan3** [comment]
@JackHaeg Tested this and the issue looks to be resolved.  I was able to edit a project and it saved.

**Comment by trillium** [comment]
Sometimes the server goes down intimately and we don't really know why right now. It would be good to provide the user a better message rather than an alert box though.

**Comment by JackHaeg** [comment]
@bkmorgan3 Did you happen to test on Prod or on Dev? 

- I assume this check was completed on Dev build (which does appear to save edits), however it regularly displays the error message "Wait! You made some changes. Are you sure you want to exit without saving?" the first time I go to save an edit. However, even if I click "Yes" in response, the edit is saved. @Spiteless There are also additional fields available on Dev that are not available on Prod (Partners, Managed by Users, Project Status, Created Date). See below:

https://github.com/hackforla/VRMS/assets/134463646/6e2419c0-e30d-4bbb-8e0c-5d79b357cea4



- On Prod I'm still having the same issue (notice that the HFLA Website URL and GitHub Identifier are not saved after I save, close and reopen the project)

https://github.com/hackforla/VRMS/assets/134463646/a8617ff2-de93-4f6d-880f-5c3953f112bb

**Comment by bkmorgan3** [comment]
Do we need to release dev to prod then?  @Spiteless  @JackHaeg

**Comment by trillium** [comment]
Worth a check, I'll rebuild front/backend of prod now

**Comment by trillium** [comment]
Rebuilt, seems like features are saving though occasionally the reply back from the DB feels long.

@JackHaeg I believe that's what might have been happening in your video, the req is out for a long time and times out, and then is resubmitted but the server is still busy.

**Comment by JackHaeg** [comment]
@Spiteless @bkmorgan3 Thanks for taking the time to make these edits. It looks like some additional fields were added & carried over (e.g., "Partners", "Managed by Users", "Project Status", and "Created Date"). I assume these are added fields that are a WIP carried over from DEV. Will confirm with the team / Bonnie what fields are necessary to include going forward. 

<details open>
<summary>Screenshot of additional fields</summary>
<br>
<img width="831" alt="Screenshot 2024-02-01 at 4 00 49 PM" src="https://github.com/hackforla/VRMS/assets/134463646/abdafcd9-7f98-49ca-b40a-a28871dd3699">
</details>

Re: the reply from the DB - let's take a look at this tonight during the All Team call. So far, I'm having a similar experience as before (edits are saved after clicking "save" > then "close", the user is presented with the warning "Wait! You made some changes. Are you sure you want to exit without saving?", even though the user has already "saved" their edits)

<details open>
<summary>Screenshot of additional fields</summary>
<br>

https://github.com/hackforla/VRMS/assets/134463646/90282c38-c3e9-4909-9063-acd65d926d3b


</details>

**Comment by JackHaeg** [comment]
- Once the following issues are completed, return to this issue and check to see if the project details page is performing as expected. Issues: (#1576 #1574 & #1577)
  - [x] Check if edits to project details are saving accordingly without 'unsaved changes' modal popping up (#1576)
  - [ ] Check if save button has a loading state (#1574)
  - [x] Check if added fields have been removed (#1577)
  - [ ] If all of the above are accomplished, close ticket.

**Comment by JackHaeg** [comment]
- Primary issue completed, moving secondary information/issues to another epic issue: #1598
