### ISSUE TITLE
Epic: Project Edit Save

### ISSUE THREAD

**Issue by JackHaeg** [hackforla/VRMS#1598]
### Overview
When saving project details, the user is presented with an 'unsaved changes' modal pop up despite their information being saved. To address this issue, a save button loading state and new logic should be implemented for the 'unsaved changes' modal.

### Action Items
  - [x] Check if edits to project details are saving accordingly without 'unsaved changes' modal popping up (#1576)
  - [x] Check if save button has a loading state (#1574)
  - [x] If all of the above are accomplished, close this epic issue.

**Comment by JackHaeg** [comment]
Epic complete
