### ISSUE TITLE
Epic: Review file tree and update MUI Components

### ISSUE THREAD

**Issue by JackHaeg** [hackforla/VRMS#1617]
### Overview
Currently, components throughout the VRMS app do not match - some use MUI styling while others do not, thus creating a fractured user experience. All components throughout the VRMS file tree below must be updated to Material-UI components. 

### What if we're unable to access the component listed?

Do your best to change the HTML elements out anyway and note in the PR that you're unable to get the component to render within VRMS for screenshots.

### Should I try to match the CSS of the app beforehand?

No, there will be some changes to the look and feel of the app switching to MUI components, we plan on going back in a second set of issues to match the CSS to our current figma design or a new figma design as it comes available. That said if functionality suffers based on MUI changes, please try to match the styling to maintain functionality (e.g., if a button previously was outlined on VRMS, then please implement an outlined MUI button). 

### Action Items
Check off these items when we have fully moved from standard HTML components to MUI components (note that same may already be updated to MUI). Each can be broken into its own issue. 
- [x] #1623
- [x] #1625
- [x] #1626
- [x] #1640
- [x] #1641
- [x] #1642
- [x] #1648
- [x] #1649
- [x] #1657
- [x] #1671 
- [x] #1672 [ closed, unused component ]
- [x] #1679 [ closed, unused component ]
- [x] #1680
- [x] #1681 [ closed, unused component ]
- [x] #1682 [ closed, unused component ]
- [x] #1683
- [x] #1684
- [x] #1693
- [x] #1694
- [x] #1698
- [x] #1699
- [x] #1700
- [x] #1701
- [x] #1724
- [x] #1665
- [x] #1703
- [x] #1704
- [x] #1705
- [x] #1707
- [x] #1708
- [x] #1709 [ closed, unused component ]
- [x] #1710
- [x] #1711
- [x] #1712
- [x] #1713
- [x] #1714
- [x] #1715
- [x] #1716
- [x] #1717
- [x] #1718
- [x] #1719
- [x] #1720
- [x] #1721
- [x] #1722

### Resources/Instructions
https://mui.com/base-ui/all-components/

**Comment by trillium** [comment]
#1549 has a list of all the files with jsx

```
./src/components/ProjectForm.js
./src/components/Navbar.js
./src/components/auth/Auth.js
./src/components/auth/HandleAuth.js
./src/components/user-admin/EditUsers.js
./src/components/user-admin/AddNewProject.js
./src/components/user-admin/UserManagement.js
./src/components/admin/donutChartContainer.js
./src/components/admin/donutChartLoading.js
./src/components/admin/dashboard/index.js
./src/components/admin/donutChart.js
./src/components/admin/reports/index.js
./src/components/dashboard/AddTeamMember.js
./src/components/dashboard/RosterTable.js
./src/components/dashboard/RosterTableRow.js
./src/components/presentational/CheckInButtons.js
./src/components/presentational/returnUserForm.js
./src/components/presentational/newUserForm.js
./src/components/presentational/profile/UserTable.js
./src/components/presentational/upcomingEvent.js
./src/components/manageProjects/eventForm.js
./src/components/manageProjects/editableField.js
./src/components/manageProjects/editMeetingTimes.js
./src/components/manageProjects/editProject.js
./src/components/manageProjects/addProject.js
./src/components/parts/form/ValidatedTextField.js
./src/components/parts/boxes/TitledBox.js
./src/components/Form.js
./src/components/Leaderboard.test.js
./src/components/Footer.js
./src/pages/Events.js
./src/pages/CheckInForm.js
./src/pages/ProjectLeaderDashboard.js
./src/pages/UserAdmin.js
./src/pages/UserProfile.js
./src/pages/ReturningUser.js
./src/pages/Home.js
./src/pages/ProjectList.js
./src/pages/ManageProjects.js
./src/pages/NewUser.js
./src/pages/SecretPassword.js
./src/App.js
```

**Comment by trillium** [comment]
Hey all, @chukalicious was asking what we should do for components that aren't being used and aren't accessible if they're in this MUI update list.

We should close those issues as unplanned and mark in the list after the issue number that the component isn't used in the current iteration of the app.

eg 

- [x] #1681 [ closed, unused component ]

And inside that issue mark it as unplanned

**Comment by JackHaeg** [comment]
@trillium Can you please close issues containing components that are not being used, add text: [ closed, unused component ] next to these issues, and make an update to this issue  within the section "What if we're unable to access the component listed."

**Comment by trillium** [comment]
@JackHaeg Done :)

**Comment by JackHaeg** [comment]
- This Epic issue was closed accidentally due to PR #1842, which linked to the epic instead of the related issue. 
- Re-opening this epic, as there are still open issues within this epic that need to be completed.

**Comment by JackHaeg** [comment]
Closing Epic as complete (all action items completed)
