### ISSUE TITLE
Update HTML components to MUI: ./src/components/auth/Auth.js

### ISSUE THREAD

**Issue by trillium** [hackforla/VRMS#1626]
### Overview
Review all components in `./src/components/Auth.js` and replace all standard HTML components with applicable MUI components.

### Action Items
- [ ] Review components in: `./src/components/Auth.js` and search for any standard HTML components.
  - _IF all components are already updated to relevant MUI:_
    - [ ] Comment on this issue that all components are already updated to MUI. 
    - [ ] Close the issue & check the box associated with this issue on the [MUI issue epic](https://github.com/hackforla/VRMS/issues/1617)  
    - [ ] Move on to the next [MUI issue](https://github.com/hackforla/VRMS/issues/1617) 
  - _IF standard HTML components are found in the file:_ 
    - [x] Replace these standard HTML components with applicable MUI components. 
    - [x] Make a PR for this file.
    - [ ] If you would like to continue working on MUI issues, move on to the next issue in the [MUI epic](https://github.com/hackforla/VRMS/issues/1617) 
- If you run into any questions, add a comment to the issue and tag "@trillium" 

### Resources
https://mui.com/material-ui/

**Comment by freaky4wrld** [comment]
@Spiteless the file has instances of <html> elements, needs to be converted to MUI-components, was trying to locally run the dev-environment, but it's not running. As suggested have tried to run the backend and fronted separately but no signs of error except warning to update `Browserslist `

```

Browserslist: caniuse-lite is outdated. Please run:
[1]   npx update-browserslist-db@latest
[1]   Why you should do it regularly: https://github.com/browserslist/update-db#readme
[1] Compiled with warnings.
[1] 
[1] ./src/pages/ManageProjects.js
[1]   Line 46:6:   React Hook useCallback has a missing dependency: 'EventsApiService'. Either include it or remove the dependency array  react-hooks/exhaustive-deps
[1]   Line 103:5:  React Hook useCallback has a missing dependency: 'EventsApiService'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

```

**Comment by freaky4wrld** [comment]
@Spiteless
-  Just want to confirm html components like `<form>, <label>, <input> and <button>` should be left alone??
- Also the link provided in the issue redirects to `Base UI` instead of `Material UI`, is it the correct one?

**Comment by JackHaeg** [comment]
@Spiteless Can you please assist Nayan on the above question?

**Comment by JackHaeg** [comment]
@Spiteless Can you please respond to Nayan's questions above when you get a chance?

**Comment by trillium** [comment]
It depends.
 - `<button>` should be replaced with the MUI `<Button>` every time
 - `<label>` can be replaced by 
   - https://mui.com/material-ui/api/input-label/
   - https://mui.com/material-ui/api/form-helper-text/
   - https://mui.com/material-ui/api/form-control-label/
- `<input>` should always be replaced, replacement changes based on type
  - text area --> https://mui.com/material-ui/react-text-field/
  - radio button --> https://mui.com/material-ui/react-radio-button/
  - 
 - `<form>` can be replaced by
   - https://mui.com/material-ui/api/form-control/

**Comment by JackHaeg** [comment]
@trillium Nayan is no longer on the VRMS team, so I am planning on un-assigning Nayan from this issue and placing it back into the prioritized backlog.

**Comment by JackHaeg** [comment]
**Hi @hollydo! When you have a moment, can you please provide an update with the following information:**
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."
  - remember to add links to the top of the issue if they are going to be needed again.

**Comment by hollydo** [comment]
Hi @JackHaeg I've been looking at other people's PR with similar tickets to see what was done and tried to follow the same components that the used for the forms. I've pushed my code and opened PR for this issue. Please take a look and give me any feedback. Thank you!

PR: https://github.com/hackforla/VRMS/pull/1848

**Comment by JackHaeg** [comment]
Thanks @hollydo!
