### ISSUE TITLE
Epic: Remove Dev Projects and replace with Prod

### ISSUE THREAD

**Issue by JackHaeg** [hackforla/VRMS#1637]
### Overview
Currently, there are too many random projects on the Dev version of VRMS, which need to be removed and replaced with a copy of the existing projects on the PROD version of VRMS.

### Action Items
- [ ] Create a script to delete the current projects and associated events from the Dev instance on MongoDB
- [ ] Create a script to copy the projects and events from the Dev instance on PROD that would clear the management field. 
- [ ] Create a script that will reinstate the saved projects from Prod to Dev.

**Comment by trillium** [comment]
@JackHaeg 

Sounds like a good option for a feature branch:

[feature.copy_prod_data](https://github.com/hackforla/VRMS/tree/feature.copy_prod_data)
