### ISSUE TITLE
Update HTML components to MUI: ./src/components/auth/HandleAuth.jsx

### ISSUE THREAD

**Issue by JackHaeg** [hackforla/VRMS#1640]
### Overview
Review all components in `./src/components/auth/HandleAuth.jsx` and replace all standard HTML components with applicable MUI components.

### Action Items
- [ ] Review components in: `./src/components/auth/HandleAuth.jsx` and search for any standard HTML components.
  - _IF all components are already updated to relevant MUI:_
    - [ ] Comment on this issue that all components are already updated to MUI. 
    - [ ] Close the issue & check the box associated with this issue on the [MUI issue epic](https://github.com/hackforla/VRMS/issues/1617) 
    - [ ] Move on to the next [MUI issue](https://github.com/hackforla/VRMS/issues/1617) 
  - _IF standard HTML components are found in the file:_ 
    - [x] Review the following PR https://github.com/hackforla/VRMS/pull/1702 that addressed multiple issues (including this one). This PR can serve as a starting point for this issue.
    - [x] Replace these standard HTML components with applicable MUI components. 
    - [x] Make a PR for this file.
    - [ ] If you would like to continue working on MUI issues, move on to the next issue in the [MUI epic](https://github.com/hackforla/VRMS/issues/1617) 
- If you run into any questions, add a comment to the issue and tag "@trillium" 

### Resources
- https://mui.com/material-ui/
- OLD closed PR: https://github.com/hackforla/VRMS/pull/1702 that addressed multiple issues (including this one). This PR can serve as a starting point for this issue.
  - Be sure to use `.jsx` instead of `.js` file extension
- This issue is part of the epic: #1617

**Comment by JackHaeg** [comment]
@nora-zajzon Does this issue have a current PR attached to it? 

If not, can you please provide a status update with the following information:
  1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
  2. Blockers: "Difficulties or errors encountered."
  3. Availability: "How much time will you have this week to work on this issue?"
  4. ETA: "When do you expect this issue to be completed?"
  5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."
    - remember to add links to the top of the issue if they are going to be needed again.

**Comment by JackHaeg** [comment]
**Update:**  
- Closed https://github.com/hackforla/VRMS/pull/1702 as this PR was out of date and included duplicate work for multiple issues. Moving this issue back to the prioritized backlog. 
- Recommend reviewing https://github.com/hackforla/VRMS/pull/1702 and using this as a jumping off point when submitting a fresh PR for this issue.

**Comment by bconti123** [comment]
Progress: Reviewed old PRs and created a starting point code, then tested the website using both regular dev tools and React dev tools. I plan to improve CSS and might work on cleaning up the code.
Blockers: N/A
Availability: 2-5 hours per week
ETA: I will complete this issue and submit my PR by Friday this week.
