### ISSUE TITLE
Update HTML components to MUI: ./src/components/user-admin/EditUsers.jsx

### ISSUE THREAD

**Issue by JackHaeg** [hackforla/VRMS#1641]
### Overview
Review all components in `./src/components/user-admin/EditUsers.jsx` and replace all standard HTML components with applicable MUI components.

### Action Items
- [x] Review components in: `./src/components/user-admin/EditUsers.jsx` and search for any standard HTML components.
  - _IF all components are already updated to relevant MUI:_
    - [x] Comment on this issue that all components are already updated to MUI. 
    - [x] Close the issue & check the box associated with this issue on the [MUI issue epic](https://github.com/hackforla/VRMS/issues/1617)
    - [ ] Move on to the next [MUI issue](https://github.com/hackforla/VRMS/issues/1617) 
  - _IF standard HTML components are found in the file:_ 
    - [ ] Review the following PR https://github.com/hackforla/VRMS/pull/1702 that addressed multiple issues (including this one). This PR can serve as a starting point for this issue.
    - [ ] Replace these standard HTML components with applicable MUI components. 
    - [ ] Make a PR for this file.
    - [ ] If you would like to continue working on MUI issues, move on to the next issue in the [MUI epic](https://github.com/hackforla/VRMS/issues/1617) 
- If you run into any questions, add a comment to the issue and tag "@trillium" 

### Resources
- https://mui.com/material-ui/
- If you run into any questions, add a comment to the issue and tag "@trillium" 
- OLD closed PR: https://github.com/hackforla/VRMS/pull/1702 that addressed multiple issues (including this one). This PR can serve as a starting point for this issue.
  - Be sure to use `.jsx` instead of `.js` file extension
- This issue is part of the epic: #1617

**Comment by JackHaeg** [comment]
**Update:** 
- Closed https://github.com/hackforla/VRMS/pull/1702 as this PR was out of date and included duplicate work for multiple issues. Moving this issue back to the prioritized backlog. 
- Recommend reviewing https://github.com/hackforla/VRMS/pull/1702 and using this as a jumping off point when submitting a fresh PR for this issue.

**Comment by bconti123** [comment]
I just moved this issue to **In Progress**. I will start to work this week.

**Comment by bconti123** [comment]
Hi @JackHaeg, I noticed that `EditUsers.jsx` was already updated from the HTML element to the MUI component in issue #1723 / PR #1727, which was merged into development.

**Comment by JackHaeg** [comment]
@bconti123 Thank you for reviewing this - we will be closing this issue as completed, as the HTML element has already been updated to MUI.
