### ISSUE TITLE
Update HTML components to MUI: ./src/components/user-admin/AddNewProject.js

### ISSUE THREAD

**Issue by JackHaeg** [hackforla/VRMS#1642]
### Overview
Review all components in `./src/components/user-admin/AddNewProject.js` and replace all standard HTML components with applicable MUI components.

### Action Items
- [x] Review components in: `./src/components/user-admin/AddNewProject.js` and search for any standard HTML components.
  - _IF all components are already updated to relevant MUI:_
    - [ ] Comment on this issue that all components are already updated to MUI. 
    - [ ] Close the issue & check the box associated with this issue on the [MUI issue epic](https://github.com/hackforla/VRMS/issues/1617) 
    - [ ] Move on to the next [MUI issue](https://github.com/hackforla/VRMS/issues/1617) 
  - _IF standard HTML components are found in the file:_ 
    - [ ] Replace these standard HTML components with applicable MUI components. 
    - [ ] Make a PR for this file.
    - [ ] If you would like to continue working on MUI issues, move on to the next issue in the [MUI epic](https://github.com/hackforla/VRMS/issues/1617) 
- If you run into any questions, add a comment to the issue and tag "@Spiteless" 

### Resources
https://mui.com/base-ui/all-components/

**Comment by JackHaeg** [comment]
Component is not being imported. Closing issue
