### ISSUE TITLE
Recruit volunteers for team open roles

### ISSUE THREAD

**Issue by JackHaeg** [hackforla/VRMS#1670]
### Dependency
- [x] need to recruit new team members to VRMS team

### Overview
We need volunteer(s) to work on the open issues we have so that we can move the project forward.

#### Creating a new role post
- [x] Copy the template post from the Community of Practice WIKI, Open Roles Templates (Resource 1.01)
- [x] Paste the template in a comment below
- [x] Customize the comment to reflect your open role
- [x] Open a new issue by using the Open Role template (Resource 1.02)
- [x] Copy and Paste your customized comment to the new issue
- [x] Add the label for the role that you are recruiting for
- [x] Submit the new issue
- [x] Assign yourself to the new issue
- [x] Add the issue to the HfLA: Open Roles project board (Resource 1.03)
- [x] add the link of the new issue to the related comment on this issue 
- [x] keep yourself assigned to this issue until the role is filled

#### Marketing the new role post
-  Post a link to the new issue in the Slack channel for the related Practice Area
   - [x] Copy the Slack message  (Resource 1.04)
   - [x] Copy the message into the [Slack Channel for the relevant Community of Practice](https://github.com/hackforla/communities-of-practice/wiki/Community-of-Practice-Slack-Channels) (The Slack channels can be found on Resource 1.01)
     - [x] Replace the text `[Replace with LINK TO NEW ISSUE]` with link to the issue
   - [x] check your team Slack channel for people reaching out after every onboarding and at least every other day

#### Once Filled
- [ ] Hide the comment on this issue for the role you just filled
- [ ] Add the following comment to the role posting issue 
  ```
  This role has been filled by @[Replace with GITHUB HANDLE OF PERSON WHO IS TAKING ROLE]
  ```
- [ ] Close the role posting issue
- [ ] Unassign yourself from this issue
- If there are no open roles on this issue (i.e., if there are open roles, there will be unclosed comments)
   - [ ] Add the label: Dependency and uncheck the dependency on top of this issue
   - [ ] Move this issue to the icebox, on the project board

### Resources/Instructions
- 1.01 [Community of Practice WIKI, Open Roles Templates, Secondary Issue](https://github.com/hackforla/communities-of-practice/wiki/Open-Roles-Templates#secondary-issue)
- 1.02 [Open new Post open role issue](https://github.com/hackforla/website/issues/new?assignees=&labels=Complexity%3A+Small%2C+feature%3A+recruiting%2C+role+missing&projects=&template=post-an-open-role.md&title=HfLA+Website%3A+Open+Role+for%3A+%5BReplace+with+NAME+OF+ROLE%5D)
- 1.03 [HfLA: Open Roles board](https://github.com/orgs/hackforla/projects/67)
- 1.04 Copy to post in CoP Slack Channels when there is an open role
   ```
   Hi, VRMS has a volunteer posting, which includes details of how to get in touch with us if you are interested. [Replace with LINK TO NEW ISSUE]
   ```

**Comment by JackHaeg** [comment]
- [x] Next steps: Copy over roles, and confirm with team if they need to be filled. 
- [x] See here for additional info: https://github.com/hackforla/communities-of-practice/wiki/Open-Roles-Templates

**Comment by JackHaeg** [comment]
#### Title
VRMS: Open Role for: Back End Developer


### Issue
- hackforla/website#1673 

#### Body
**Project Name**: VRMS

**Name of Role**: Back End Developer

**Volunteer Opportunity**: We are looking for a developer who has some experience with mongoDB and would be interested in assisting us with setting migrations and refactoring our database structure

**Duration**: Open-ended (min 2 months) 

**Meeting Times**: All Team Meeting Mondays 7-8pm Pacific

**Who to communicate your interest to**
- Slack channel link: [#vrms](https://hackforla.slack.com/archives/CRGH5HM0Q)
- Slack name of person to contact in the channel: see who this issue is assigned to and @ message them in the channel above

[Read more about the project](https://www.hackforla.org/projects/vrms)

**Comment by JackHaeg** [comment]
#### Title
VRMS: Open Role for: Mid Level Full Stack Developer


### Issue
- https://github.com/hackforla/website/issues/7570

#### Body
**Project Name**: VRMS

**Name of Role**: Full Stack Developer

**Volunteer Opportunity**: We are looking for multiple developers with intermediate experience in front end and back end development. This is a project where we plan to manage and store information about volunteers, projects, and events. This can become the reason why Hack for LA works.

**Duration**: Open-ended (min 2 months)

**Meeting Times**: All Team Meeting (Mondays 7-8pm Pacific)

**Who to communicate your interest to**
- Slack channel link: [#vrms](https://hackforla.slack.com/archives/CRGH5HM0Q)
- Slack name of person to contact in the channel: see who this issue is assigned to and @ message them in the channel above

[Read more about the project](https://www.hackforla.org/projects/vrms)

**Comment by JackHaeg** [comment]
#### Title
VRMS: Open Role for: Product Manager


### Issue
- https://github.com/hackforla/VRMS/issues/1809

#### Body
**Project Name**: VRMS

**Name of Role**: Product Manager

**Volunteer Opportunity**: We need structure! We are a scrappy group of developers who are inspired but a little lost when it comes to planning. We want someone to run the board, the weekly meeting, and have a clear plan for how we can make this project succeed. This is a project where we plan to manage and store information about volunteers, projects, and events. This can become the reason why Hack for LA works.

**Duration**: Open-ended (min 3 months) 

**Meeting Times**: 
- All Team: Mondays 7-8pm Pacific
- Planning (PMs / Design): Thursdays 4-5pm Pacific

**Who to communicate your interest to**
- Slack channel link: [#vrms](https://hackforla.slack.com/archives/CRGH5HM0Q)
- Slack name of person to contact in the channel: see who this issue is assigned to and @ message them in the channel above

[Read more about the project](https://www.hackforla.org/projects/vrms)

**Comment by ExperimentsInHonesty** [comment]
# Role posts from the Previous Product Management Open Roles board, Filled column

## Post 1
<details><summary>copy code</summary>

```
<img src="https://www.hackforla.org/assets/images/projects/vrms.png" />

**Project Name** : VRMS (Volunteer Relationship Management System)

**About the Project:** Arguably the awesomest project in hack for la! This is a project where we plan to manage and store information about volunteers, projects, and events. This can become the reason why hack for la works.

**Volunteer Opportunity:** We need structure! We are a scrappy group of developers who are inspired but a little lost when it comes to planning.

**Responsibilities:**  We want someone to run the board, the weekly meeting, and have a clear plan for how we can make this project succeed.

**Duration:** Ongoing, 6 hours per week

**Meetings:**
- Monday 7-8pm PST (Mandatory)
- Thursday 6:30-7:30pm PST (Optional Dev Meeting) (You would not run this one)

**Who to communicate your interest to**
Slack channel [#vrms](https://hackforla.slack.com/archives/CRGH5HM0Q)
Contact Josh Bubar, or Trillium Smith
```
</details> 

<details><summary>viewable code</summary>

<img src="https://www.hackforla.org/assets/images/projects/vrms.png" />

**Project Name** : VRMS (Volunteer Relationship Management System)

**About the Project:** Arguably the awesomest project in hack for la! This is a project where we plan to manage and store information about volunteers, projects, and events. This can become the reason why hack for la works.

**Volunteer Opportunity:** We need structure! We are a scrappy group of developers who are inspired but a little lost when it comes to planning.

**Responsibilities:**  We want someone to run the board, the weekly meeting, and have a clear plan for how we can make this project succeed.

**Duration:** Ongoing, 6 hours per week

**Meetings:**
- Monday 7-8pm PST (Mandatory)
- Thursday 6:30-7:30pm PST (Optional Dev Meeting) (You would not run this one)

**Who to communicate your interest to**
Slack channel [#vrms](https://hackforla.slack.com/archives/CRGH5HM0Q)
Contact Josh Bubar, or Trillium Smith
</details>

**Comment by ExperimentsInHonesty** [comment]
# Role posts from the Previous Ops Open Roles board, Site Reliability Engineer column

## Post 1

```
VRMS

looking for SRE
```

**Comment by ExperimentsInHonesty** [comment]
# Role post from the Previous Engineering Open Roles board, Back End  column



**Project Name**: Hackforla.org Website

**Volunteer Opportunity**: Need someone with experience with GitHub actions automation, Google AppsScript, and working with REST and GraphQL calls. The developer will work very closely with the VRMS and CivicTechJobs teams, who manages the data we receive. **Note:** The Website project is unique in that it is hosted on GitHub Pages. This means we do not have an official backend.

**Duration**: Open-ended

**Meeting times**:  See project page below

**Who to communicate your interest to**
- Slack channel link: #hfla-site
- Slack name of person to contact in the channel: RW

[Read more about the project](https://www.hackforla.org/projects/website)

**Resources:**
[Welcome to the HackforLA.org (HfLA) Website Wiki!](https://github.com/hackforla/website/wiki)
[VRMS](https://www.hackforla.org/projects/vrms)

**Comment by JackHaeg** [comment]
#### Title
VRMS: Open Role for: Full Stack Developer


### Issue
- https://github.com/hackforla/VRMS/issues/1922

#### Body
You are only allowed to join **one** team.
- If you would like to observe this team before you join, please let the person who is recruiting for this posting know you are in observation mode (not onboarding)

![image](https://github.com/user-attachments/assets/95345e9b-75eb-4032-9e7f-b0b2b8aaa914)

**Project Name**: VRMS

**Name of Role**: Full Stack Developer

**Volunteer Opportunity**: We are looking for multiple developers with intermediate experience in front end and back end development. This is a project where we plan to manage and store information about volunteers, projects, and events. This can become the reason why Hack for LA works.

**Tech stack:** 
- Backend written in JavaScript with Express
- Frontend using React and Vite. 
- Built and deployed using GitHub Actions, Docker, AWS.

**Duration**: Open-ended (min 3 months)

**Meeting Times**: All Team Meeting (Mondays 7-8pm Pacific)

**Who to communicate your interest to**
- Slack channel link: [#vrms](https://hackforla.slack.com/archives/CRGH5HM0Q)
- Slack name of person to contact in the channel: message `@Trillium Smith` or `@Jack Haeger`

[Read more about the project](https://www.hackforla.org/projects/vrms)

**Comment by JackHaeg** [comment]
#### Title
VRMS: Open Role for: DevOps Engineer


### Issue
- #1998

#### Body
You are only allowed to join one team.
- If you would like to observe this team before you join, please let the person who is recruiting for this posting know you are in observation mode (not onboarding)

<img width="600" height="400" alt="Image" src="https://github.com/user-attachments/assets/b5dd8335-3bdc-42a1-9ff6-27b4395aee03" />


**Project Name**: VRMS

**About**: VRMS is a browser-based software tool created by Hack for LA (HfLA) for volunteer organizations to curate participant journeys and further organizational goals of workforce development and project impact. By collecting and using relevant data, VRMS is able to automate repetitive tasks; match volunteers with projects, relevant training and job opportunities; measure engagement with projects and activities; and surface insights to improve organizational effectiveness and the volunteer experience over time.

**Volunteer Opportunity**: We are looking for a DevOps engineer to aid in helping resolving AWS issues, GitHub workflows and build setup.

**Duration**: On-going

**Meeting Times**: 
_- All Team Meeting_: Monday 7-8pm PST (required)
_- DevOps Meeting_: Wednesday 6-7pm PST (required)

**Who to communicate your interest to**
- Slack channel link: [#VRMS](https://hackforla.slack.com/archives/CRGH5HM0Q)
- Slack name of person to contact in the channel: see who this issue is assigned to and @ message them in the channel above

[Read more about the project](https://www.hackforla.org/projects/vrms)

**Comment by JackHaeg** [comment]
#### Title
VRMS: Open Role for: Lead Product Manager


### Issue
- #2088 

#### Body
You are only allowed to join one team.
- If you would like to observe this team before you join, please let the person who is recruiting for this posting know you are in observation mode (not onboarding)

<img width="600" height="400" alt="Image" src="https://github.com/user-attachments/assets/b5dd8335-3bdc-42a1-9ff6-27b4395aee03" />



**Project Name**: VRMS

**About**: VRMS is a browser-based software tool created by Hack for LA (HfLA) for volunteer organizations to curate participant journeys and further organizational goals of workforce development and project impact. By collecting and using relevant data, VRMS is able to automate repetitive tasks; match volunteers with projects, relevant training and job opportunities; measure engagement with projects and activities; and surface insights to improve organizational effectiveness and the volunteer experience over time.

**Volunteer Opportunity**: We need structure! We are a scrappy group of developers who are inspired but a little lost when it comes to planning. We want someone to run the board, the weekly meeting, and have a clear plan for how we can make this project succeed. This is a project where we plan to manage and store information about volunteers, projects, and events. This can become the reason why Hack for LA works.

**Duration**: Open-ended (min 3 months)

**Meeting Times**: 
_- All Team Meeting_: Monday 7-8pm PST (required)
_- Planning (PMs/Design)_: Thursdays 4-5pm PST (required)

**Who to communicate your interest to**
- Slack channel link: [#VRMS](https://hackforla.slack.com/archives/CRGH5HM0Q)
- Slack name of person to contact in the channel: see who this issue is assigned to and @ message them in the channel above

[Read more about the project](https://www.hackforla.org/projects/vrms)
