### ISSUE TITLE
Update HTML components to MUI: ./src/components/admin/dashboard/index.jsx

### ISSUE THREAD

**Issue by JackHaeg** [hackforla/VRMS#1671]
### Overview
Review all components in`./src/components/admin/dashboard/index.jsx` and replace all standard HTML components with applicable MUI components.

### Action Items
- [x] Review components in:`./src/components/admin/dashboard/index.jsx` and search for any standard HTML components.
  - _IF all components are already updated to relevant MUI_
    - [ ] Comment on this issue that all components are already updated to MUI. 
    - [ ] Close the issue & check the box associated with this issue on the [MUI issue epic](https://github.com/hackforla/VRMS/issues/1617)
    - [ ] Move on to the next [MUI issue](https://github.com/hackforla/VRMS/issues/1617) 
  - _IF standard HTML components are found in the file:_ 
    - [x] Review the following PR, which can serve as the starting point for this issue: #1677 
    - [x] Replace these standard HTML components with applicable MUI components. 
    - [x] Make a PR for this file
    - [ ] If you would like to continue working on MUI issues, move on to the next issue in the [MUI epic](https://github.com/hackforla/VRMS/issues/1617) 

### Resources
- https://mui.com/material-ui/
- OLD closed PR: https://github.com/hackforla/VRMS/pull/1677. 
  - This PR can serve as. a starting point for this issue. 
  - Be sure to use `.jsx` instead of `.js` file extension in PR
- If you run into any questions, add a comment to the issue and tag "@trillium"
- This issue is part of the epic: #1617

**Comment by trillium** [comment]
Edit

Spoke too soon, this component needs changes

**Comment by JackHaeg** [comment]
@chukalicious Moved this issue back to "in progress" as this issue is still in progress, and has an active PR that is currently under review. Once the PR is merged, the issue will close automatically.

**Comment by JackHaeg** [comment]
**Update:**
- PR closed: https://github.com/hackforla/VRMS/pull/1677, as the PR was out of date and included a file extension (`.js` instead of .`jsx`) that was incompatible with our current repo. 
  - Issue has been added back to prioritized backlog to be picked up by a developer
