### ISSUE TITLE
Finalize Project Status Designs

### ISSUE THREAD

**Issue by juliagab56** [hackforla/VRMS#1678]
### Overview
We want to add a new feature so the user can change the status of a project. This will allow them to delete and archive projects too.
 
### Action Items
- [ ] Refine modals:
    - [x] Update fonts on V2 “Deleted” modals and refine design to ensure that modals mostly fit with existing design approach.
    - [x] Update to ensure all previous modals and updated modals look uniform (using the V2 “deleted” as a reference).
    - [ ] Consider adding relevant icons to V2 “Deleted” modals.
- [ ] Annotate figma designs to highlight to devs what they need to focus on adding to each screen, as well as explain functionality and interactions (e.g., what happens when users interact with elements such as buttons and inputs). 
- [ ] Use the same modal flow used in the “Complete flow” (i.e., the one with 2 options clearly outlined) across all "EDIT EXISTING PROJECT STATUS" flows.
  - [ ] NEW: Move the "Modal message/Delete events first" modal within the "EDIT EXISTING PROJECT STATUS" flows to be displayed directly after the user selects a project status other than "Active" (see [Figma comment](https://www.figma.com/design/pIxFTL62Nx2XyQdZy1fR6f?node-id=3040-7993#900726199))
  - [ ] Also, after the "Modal message/Delete events first" modal is displayed, show the initial "Edit Project Status" screen with the project status "Active" selected (i.e., the same screen that starts the flow). Follow this approach on all "Edit Project Status" screens after the "Modal message/Delete events first" modal. [Figma comment](https://www.figma.com/design/pIxFTL62Nx2XyQdZy1fR6f?node-id=3040-7151#900726864)
- [ ] Use screenshots as a reference to update the screens within the “View Project Status” to ensure that devs do not redesign the whole screen. See [Figma Comment](https://www.figma.com/design/pIxFTL62Nx2XyQdZy1fR6f?node-id=3040-8620#900733643)

### Resources/Instructions
[Figma](https://www.figma.com/design/pIxFTL62Nx2XyQdZy1fR6f/%F0%9F%96%8C%EF%B8%8FVRMS-Design%F0%9F%96%8C%EF%B8%8F?node-id=3108-13257&t=YPRvQe0K0GfI6ysW-4)

**Please review the requirements and status descriptions below:**
<details><summary>Requirements</summary>
<p>

- Only Admins can make status changes (PMs cannot make changes)
- When a Admin creates a new project, the status will be active by default. If the admin wants to change the status they need to do it with the dropdown. 
- Select only one status at a time.

</p>
</details> 

<details><summary>Active</summary>
<p>

- A project being currently worked on. 
- Has assigned team members.
- Has meetings.

</p>
</details> 

<details><summary>On Hold</summary>
<p>

- A project that we might bring back in the future. It is waiting to be prioritized. 
- IF there are recurring events still associated with the project, a will modal be displayed stating "Please delete this project's recurring event(s). Projects cannot be “On Hold” if they have any open events."

</p>
</details> 

<details><summary>Completed</summary>
<p>

- A project that we have wrapped up.
- IF there are recurring events still associated with the project, a will modal be displayed stating "Please delete this project's recurring event(s). Projects cannot be Completed if they have any open events."

</p>
</details> 

<details><summary>Closed</summary>
<p>

- A project that did not get completed and that we will not be reactivating.
- IF there are recurring events still associated with the project, a will modal be displayed stating "Please delete this project's recurring event(s). Projects cannot be Archived if they have any open events."

</p>
</details> 

<details><summary>Deleted</summary>
<p>

- A project that was created as a test or by mistake, or otherwise is not real.
      - Note that selecting "Delete" results in a modal popping up, asking the user to confirm "Do you want to delete this project?" Yes / No
      - IF there are recurring events still associated with the project, a modal will be displayed stating "Please delete this project's recurring event(s). Projects cannot be deleted if they have any open events."
      - 90 days to restore a project

</p>
</details>

**Comment by JackHaeg** [comment]
Issue is completed. Final designs here: [Figma](https://www.figma.com/design/pIxFTL62Nx2XyQdZy1fR6f/%F0%9F%96%8C%EF%B8%8FVRMS-Design%F0%9F%96%8C%EF%B8%8F?node-id=3108-13257&t=YPRvQe0K0GfI6ysW-4)
