### ISSUE TITLE
Epic - User Permission Search

### ISSUE THREAD

**Issue by JackHaeg** [hackforla/VRMS#1737]
### Overview
We need to provide more transparency for Admins on VRMS who need to view and manage permissions for existing users. Currently, there is no way for admins to see a list of other admins on the VRMS app, or a list of users with Project Management (PM) access to specific projects. This epic issue tracks the creation of a new "Permission Search" feature that allows admins to view a list of all other admins on VRMS and a list of PM users and their linked projects, as well as feature that enables Admins to promote or demote users to Admin permission level.

### Action Items - follow these steps IN ORDER, please :)
- [x] Create the "VRMS Admin" component within the "EditUsers" screen (#1486)
- [x] #1747
   - [x] Test functionality on Dev with stakeholder.
- [x] #1770
- [x] #1769
  - [x] #1771
- [x] #1751
- [x] #1752
  - [x] #1754
  - [x] #1801
    - [x] #1836
- [x] Test functionality on Dev with stakeholder. If approved, rebuild PROD. 

- For each of these steps, create a PR against the [user_permissions_search branch](https://github.com/hackforla/VRMS/tree/user_permissions_search). Once everything is up and running, we'll add this feature branch to `development`
  - [x] #1774 
  - [x] #1798 
  - [x] #1808 
  - [x] #1810 
  - [x] #1799 
  - [x] PR for #1801 
- [x] Link up all additions of User Permission Search from the 5 PRs above and resolve any merge issues
  - [x] Confirm resolution of components UserPerssions and UserPermissionsSearch in 
    - [x] NavBar
    - [x] AppJs

### Resources/Instructions
- [Low-fi mockups created by Bonnie / Jack](https://docs.google.com/presentation/d/1oPP7mXDb09le3vVyaB4YUzOYYDa7sqDVCmvW5Srg30k/edit?usp=sharing)
- Use [MUI styling](https://mui.com/) on all components.

**Comment by JackHaeg** [comment]
Issue was re-written and added to another issue for this epic. Closing as unplanned.

**Comment by JackHaeg** [comment]
Jack to Demo with Bonnie and close

**Comment by JackHaeg** [comment]
All steps in the User Permission Search Epic have been completed and deployed to Dev as of 3.26.2025. These changes will be deployed to PROD the next time PROD is rebuilt.
