### ISSUE TITLE
Create milestones and labels

### ISSUE THREAD

**Issue by switchzer0** [hackforla/VRMS#228]
### Overview
Phase MVP requirement tickets into milestones

### Action Items
- [x] review all features
- [x] determine milestone periods
- [x] create milestones in GitHub
- [x] review and clean up existing labels in GitHub
- [x] create new labels in GitHub
- [x] apply to all tickets

### Blockers
#255 Revised Roadmap/MVP phasing
#225 Update PRD

### Resources
- [Feature List](https://docs.google.com/spreadsheets/d/1VCuDRxwcLsT3q1NWtfYevg0TDcfpMhtZQpTRkyT2_2Q/edit#gid=286827311)
- [Check for missing roles](https://github.com/hackforla/VRMS/issues?q=is%3Aopen+is%3Aissue+-label%3A%22role%3A+Back+End%22+-label%3A%22role%3A+devops%22+-label%3A%22role%3A+Front+End%22+-label%3A%22role%3A+Missing%22+-label%3A%22role%3A+Product%22)
- [Check for missing size](https://github.com/hackforla/VRMS/issues?q=is%3Aopen+is%3Aissue+-label%3A%22size%3A+1pt%22+-label%3A%22size%3A+2pt%22+-label%3A%22size%3A+3pt%22+-label%3A%22size%3A+5pt%22+-label%3A%22size%3A+missing%22)
- [Check for issues not assigned to a project](https://github.com/hackforla/VRMS/issues?q=is%3Aissue+is%3Aopen+no%3Aproject)

**Comment by switchzer0** [comment]
### progress
finished initial triage of feature list w/ bonnie, ready to finalize w/ Alex (1–2hr meeting needed to discuss)

### blockers
scheduling

### availability
Adam: weekend and beyond
Bonnie: ?

**Comment by switchzer0** [comment]
### progress
reviewed feature list with Alex. next will integrate features into updated PRD

### blockers
Adam's schedule

### availability
Adam: after tuesday of this week

### ETA
next week's meeting or the following one

**Comment by switchzer0** [comment]
### Progress
New blockers have delayed PRD which delays milestones.

blockers
#225 revised roadmap/MVP phasing
#255 requirements doc

availability
Adam: flex

ETA
2 weeks

**Comment by switchzer0** [comment]
unblocked as of today. Will discuss with @alex-anakin this week.

**Comment by switchzer0** [comment]
milestones created. @alex-anakin to revise as needed, review/draft labels, and apply milestones/labels to existing issues before closing issue.

**Comment by maburke09** [comment]
At team meeting, let's discuss where the following issues need to go:

https://github.com/hackforla/VRMS/issues?q=is%3Aissue+is%3Aopen+no%3Aproject

**Comment by drubgrubby** [comment]
This functionality has been completed and the ticket is no more.
