### ISSUE TITLE
v0.4 Setup Infrastructure Epic

### ISSUE THREAD

**Issue by jasonwong26** [hackforla/VRMS#635]
# Story
There is no story for this epic.  This contains a number of tasks related to preparing the v0.4 branch for general development.

# Tickets

## Environment
- [x] #645
- [x] #646
- [x] #647
- [x] #648
- [x] #649
- [x] #650
- [x] #651
- [x] #653 

## Database
- [ ] #659
- [x] #660

## Linting
- [x] Copy over linting rules from development branch
- [x] #688

### Backend
- [x] #686
- [x] Address warnings for rule: max-len
- [ ] Address warnings for rule: no-prototype-builtins
- [ ] Address warnings for rule: no-undef
- [ ] Address warnings for rule: no-unused-vars

### Frontend
- [x] #687
- [ ] Address warnings for rule: camelcase
- [ ] Address warnings for rule: import/extensions
- [ ] Address warnings for rule: import/newline-after-import
- [ ] Address warnings for rule: import/no-duplicates
- [ ] Address warnings for rule: import/no-extraneous-dependencies
- [ ] Address warnings for rule: import/no-named-as-default-member
- [ ] Address warnings for rule: import/order
- [ ] Address warnings for rule: import/prefer-default-export
- [ ] Address warnings for rule: jest/expect-expect
- [ ] Address warnings for rule: jest/no-standalone-expect
- [ ] Address warnings for rule: jest/valid-expect
- [ ] Address warnings for rule: jest/valid-title
- [ ] Address warnings for rule: jest-dom/prefer-checked
- [ ] Address warnings for rule: jest-dom/prefer-enabled-disabled
- [ ] Address warnings for rule: jest-dom/prefer-in-document
- [ ] Address warnings for rule: jsx-a11y/click-events-have-key-events
- [ ] Address warnings for rule: jsx-a11y/label-has-associated-control
- [ ] Address warnings for rule: jsx-a11y/no-static-element-interactions
- [ ] Address warnings for rule: max-classes-per-file
- [ ] Address warnings for rule: no-nested-ternary
- [ ] Address warnings for rule: no-param-reassign
- [ ] Address warnings for rule: no-return-await
- [ ] Address warnings for rule: no-shadow
- [ ] Address warnings for rule: no-unused-expressions
- [ ] Address warnings for rule: no-unused-vars
- [ ] Address warnings for rule: no-use-before-define
- [ ] Address warnings for rule: prefer-const
- [ ] Address warnings for rule: prefer-destructuring
- [ ] Address warnings for rule: prefer-promise-reject-errors
- [ ] Address warnings for rule: prettier/prettier
- [ ] Address warnings for rule: react/button-has-type
- [ ] Address warnings for rule: react/no-array-index-key
- [ ] Address warnings for rule: react/no-unescaped-entities
- [ ] Address warnings for rule: react-hooks/exhaustive-deps
- [ ] Address warnings for rule: spaced-comment
- [ ] Address warnings for rule: testing-library/no-node-access

## Miscellaneous
- [ ] Remove references to `cypress` test platform
- [ ] Remove references to `http-proxy-middleware` package
- [ ] Update README with instructions for using local Docker environment
- [x] #666
- [ ] Update Contributing document to instruct folks to merge PRs to v0.4 Branch
- [ ] Update README for v0.4

**Comment by jasonwong26** [comment]
Ticket is for brainstorming / tracking all infrastructure tasks for setting up v0.4 for feature development

## Pending Tasks
- [ ] Set up v4 PR / Push GitHub action
- [ ] Set up MongDb docker container
  - [ ] Add seed data script
  - [ ] Integrate with Docker compose file
- [ ] Eliminate React App Proxy (only use nginx)
- [ ] Set up API Documentation
- [ ] Update outdated NPM references
- [ ] Eliminate Cypress and other legacy script commands
- [ ] Set up linting rules

**Comment by maburke09** [comment]
@jasonwong26 I have made all the tickets for the back-end and front-end. They should all be on the board now.

**Comment by jasonwong26** [comment]
That's great, thank you @maburke09!

Would you mind linking them back to this epic?  (this would replace the checkbox items in the eslint section). Alternatively, if you and Bonnie don't want to use epics in the future we can just delete the checkbox items.  Bottom line, we shouldn't have multile ways of tracking whether the eslint issues are resolved!

**Comment by ExperimentsInHonesty** [comment]
Hi @jasonwong26 we have added the feature: eslint warnings label to all the issues created here.  The benefit of this method is in addition to being able to see all the issues, you can actually see where they are on the project board.  So for instance, if you click on this link you will see that all the issues are in the prioritized backlog, and none have been assigned 
[Filtering the project board by the label "feature: eslint warnings"](https://github.com/hackforla/VRMS/projects/10?card_filter_query=label%3A%22feature%3A+eslint+warnings%22)
