### ISSUE TITLE
Integrate with AWS Cognito for Authorization

### ISSUE THREAD

**Issue by jasonwong26** [hackforla/VRMS#636]
# Story

> 1.01 Landing/Login Page
1.02 | Landing/Login Page - Sign In
1.03 | Landing/Login Page - Magic Link Authorization
1.04 | Landing/Login Page -   Cookie Recognition
1.05 | Landing/Login Page - Text Field Memory
2.03 | Main Dashboard - Logout

This ticket tracks the work needed to integrate with AWS Cognito to enhance user security and authentication experience.  These include:

- User Authentication (1.01, 1.02)
- Extended Session Management - up to 30 days (1.04, 1.05)
- Log Out Session (2.03)
- User Signup (3.01)
- Email Verification (3.02)

AWS Cognito is free for up to 50,000 monthly active users (see pricing link below for details).

# Reference
[Cognito Pricing](https://aws.amazon.com/cognito/pricing/)
[Styling Built-In Cognito Authentication pages](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-app-ui-customization.html)
[Integrating Custom Authentication pages with Cognito](https://docs.amplify.aws/lib/auth/customui/q/platform/js)

# Tickets

## Administrative Tasks
- [x] #637

## Frontend Tasks (Phase 1)
- [x] #640
- [x] #641
- [x] #643

## Backend Tasks (Phase 1)
- [x] #638
- [x] #639
- [x] #642

## Putting it all together
- [x] #644

## Frontend Tasks (Phase 2)
- [ ] Create an requiresAuthentication enhancer
- [ ] Modify existing user login screen with AWS Cognito
- [ ] Modify existing user logout screen with AWS Cognito
- [ ] Modify existing new user creation screens with AWS Cognito
