### ISSUE TITLE
Address outdated NPM packages and audit warnings in Backend

### ISSUE THREAD

**Issue by jasonwong26** [hackforla/VRMS#651]
# v0.4 Setup Infrastructure

This ticket addresses NPM warnings related to versions and security.

# Dependencies
- #645

# Instructions
- [x] Run the `npm outdated` script.  Document all of the warnings that are returned.
- [x] Address each warning:
  - for minor package updates - go ahead and update to the latest version
  - form major package updates - research the package version change to identify (as best you can) the breaking changes.  Raise the version change as a topic for discussion in a team meeting.
- [x] Run the `npm audit` or `yarn outdated` script.  Document all of the warnings that are returned.  Hopefully most issues will be resolved via addressing the outdated packages, but for those that remain Raise these as a topic for discussion in a team meeting.
- [ ] Apply all major package updates that the team feels are worth pursuing.  Address any build errors that occur due to the changes.

# Acceptance Criteria
Running the `npm outdated` and `yarn audit` commands should pass without error (unless the group decides that it is out of scope to address an issue for a given package).

**Comment by vadzimk** [comment]
@jasonwong26
Suppose no changes are necessary in backend.

vrms\backend>npm audit
                                                                                
                       === npm audit security report ===                        
                                                                                
```
found 0 vulnerabilities
 in 1179 scanned packages
```

vrms\backend>npm outdated
```
Package                 Current  Wanted  Latest  Location
@shelf/jest-mongodb       1.3.4   1.3.4   2.0.1  vrms-server
@slack/bolt               2.7.0   2.7.0   3.5.0  vrms-server
concurrently              5.3.0   5.3.0   6.2.1  vrms-server
dotenv                    8.6.0   8.6.0  10.0.0  vrms-server
eslint-config-prettier   6.15.0  6.15.0   8.3.0  vrms-server
googleapis               59.0.0  59.0.0  84.0.0  vrms-server
helmet                   3.23.3  3.23.3   4.6.0  vrms-server
jest                     26.6.3  26.6.3  27.0.6  vrms-server
mongodb-memory-server     6.9.6   6.9.6   7.3.6  vrms-server
supertest                 4.0.2   4.0.2   6.1.5  vrms-server
```

**Comment by jasonwong26** [comment]
Hi @vadzimk!

Here's the results I get on my machine for the backend (note: development-0.4 branch):

## yarn audit
![image](https://user-images.githubusercontent.com/4618259/129807848-b596aeaf-aa92-4670-b35f-2a972477f9bc.png)

## yarn outdated
![image](https://user-images.githubusercontent.com/4618259/129807906-d2b8e9cd-4a26-4cc5-a61c-13c14b567703.png)

Note the color schemes - green and yellow indicate non-breaking changes.  Red items include breaking changes.  Part of this ticket is to document the packages with likely breaking changes so we can decide as a team how to approach each.

Last quick note - you'll want to address the non-breaking outdated packages first.  This should resolve the majority of the audit warnings!

**Comment by vadzimk** [comment]
@jasonwong26 
We are looking at different lock files while running `npm outdated` and `yarn outdated`: package-lock.json and yarn.lock respectively.

I recently installed from scratch all dependencies with `npm install` and `npm outdated` reports different versions from what `yarn outdated` reports ( i am not using yarn at all - someone else installed and pushed yarn.lock file to github repo for their development a while ago). 
Hence, version hints in the package.json allow for wanted versions and latest versions are major releases with potentially breaking code as `npm outdated` correctly reported. One can run npm update on their machine to update to patch and minor releases. Each time you push to production it happens automatically in the CI.

No vulnerabilities are reported by `npm audit` either.

*Reference: https://stackoverflow.com/questions/58518471/npm-audit-versus-yarn-audit*

Regarding updating npm packages to the latest releases (new major version while tests pass),
I ran `ncu --doctor -u` 
It ensures that tests pass with the new version rules.
Proposed changes are in my PR below

*Reference: https://nodejs.dev/learn/update-all-the-nodejs-dependencies-to-their-latest-version*

**Comment by jasonwong26** [comment]
# Packages with Major version changes:
## Unused packages (holdovers from v0.3)
- @slack/bolt@3.5.0 - not used
- googleapis@84.0.0 - not used
- helmet@4.6.0 - not used
- concurrently@6.2.1 - not used

## In use packages
- @shelf/jest-mongodb@2.0.1 - changed from version @1.2.3, no issues with updating major version
- supertest@6.1.6 - changed from version @4.0.2, no issues with updating major version

**Comment by jasonwong26** [comment]
# Package Changes:

## Updated minor and patch versions
- `async` 3.2.0 => 3.2.1
- `debug` 4.1.1 => 4.3.2
- `eslint` 7.9.0 => 7.32.0

## Major Version changes (requires discussion)
| Package | Current | Wanted | Latest | Package Type | Package URL |
| --- | --- | ---| --- | --- | --- |
| dotenv | 8.6.0   | 8.6.0  | 10.0.0 | dependencies    | https://github.com/motdotla/dotenv#readme | 
| mongoose             | 5.13.8  | 5.13.8 | 6.0.4  | dependencies    | https://mongoosejs.com | 
| @shelf/jest-mongodb   | 1.3.4   | 1.3.4  | 2.0.3  | devDependencies | https://github.com/shelfio/jest-mongodb.git | 
| concurrently          | 5.3.0  | 5.3.0  | 6.2.1  | devDependencies | https://github.com/open-cli-tools/concurrently#readme | 
| jest                  | 26.6.3  | 26.6.3 | 27.1.0 | devDependencies | https://jestjs.io/ | 
| mongodb               | 3.7.0  | 3.7.0  | 4.1.1  | devDependencies | https://github.com/mongodb/node-mongodb-native | 
| mongodb-memory-server | 6.9.6  | 6.9.6  | 7.4.0  | devDependencies | https://github.com/nodkz/mongodb-memory-server | 
| supertest             | 4.0.2  | 4.0.2  | 6.1.6  | devDependencies | https://github.com/visionmedia/supertest#readme | 

### Removed Unused Packages
- `@slack/bolt`
- `cors`
- `eslint-config-airbnb`
- `eslint-config-airbnb-base`
- `eslint-config-prettier`
- `eslint-plugin-import`
- `eslint-plugin-jsx-a11y`
- `eslint-plugin-react`
- `express-validator`
- `googleapis`
- `helmet`
- `prettier`
- `pretty-quick`
- `why-is-node-running`

### Other Changes
- `nodemailer` - moved to devDependencies (not used in Production code)
- `mongodb-memory-server` - moved to devDependencies (not used in Production code)
  - iterated version to latest non-major version change: 6.9.6
- `mongodb` - added peer dependency for `mongodb-memory-server`
- `babel-eslint` - replaced deprecated package with replacement: `@babel/eslint-parser`

# Package Audit
All audit warnings have been addressed.

# Suggested next steps:
1. Create separate tickets for each above package with a major version change. (some will require moderate code rewrites)
2. Address each of the created tickets.
3. Rerun the `yarn audit` script to confirm that all warnings are addressed.

**Comment by jasonwong26** [comment]
Hi @ExperimentsInHonesty,

Assigning to you to create individual tickets for addressing the following outdated packages that require major version changes. For each, we want a developer to update to the latest version of the package, then:

1. Ensure the project builds and runs
2. Ensure that all unit tests pass
3. Ensure that there are no lint errors

| Package | Current | Wanted | Latest | Package Type | Package URL | Issue
| -- | -- | -- | -- | -- | -- | -- | 
| dotenv | 8.6.0 | 8.6.0 | 10.0.0 | dependencies | https://github.com/motdotla/dotenv#readme | #745 
| mongoose | 5.13.8 | 5.13.8 | 6.0.4 | dependencies | https://mongoosejs.com | #746
| @shelf/jest-mongodb | 1.3.4 | 1.3.4 | 2.0.3 | devDependencies | https://github.com/shelfio/jest-mongodb.git | #747
| concurrently | 5.3.0 | 5.3.0 | 6.2.1 | devDependencies | https://github.com/open-cli-tools/concurrently#readme | #748
| jest | 26.6.3 | 26.6.3 | 27.1.0 | devDependencies | https://jestjs.io/ | #749
| mongodb | 3.7.0 | 3.7.0 | 4.1.1 | devDependencies | https://github.com/mongodb/node-mongodb-native | #750
| mongodb-memory-server | 6.9.6 | 6.9.6 | 7.4.0 | devDependencies | https://github.com/nodkz/mongodb-memory-server | #751
| supertest | 4.0.2 | 4.0.2 | 6.1.6 | devDependencies | https://github.com/visionmedia/supertest#readme | #752

**Comment by ExperimentsInHonesty** [comment]
@jasonwong26 I made the backend issues
